overrides: "git://github.com/pyexcel/pyexcel-mobans!/mobanfile.yaml"
configuration:
  configuration: pyexcel-handsontable.yml
targets:
  - README.rst: README.rst
  - .gitignore: gitignore.jj2
  - "pyexcel_handsontable/templates/css.html": "handsontable/style.css.jj2"
  - "docs/source/index.rst": "docs/source/index.rst"
  - "docs/source/conf.py": "docs/source/conf.py.jj2"
