configuration:
  configuration_dir: "commons/config"
  template_dir:
  - "commons/templates"
  - ".moban.d"
  configuration: pyexcel-handsontable.yml
targets:
  - README.rst: README.rst
  - setup.py: setup.py
  - requirements.txt: requirements.txt
  - LICENSE: LICENSE.jj2
  - MANIFEST.in: MANIFEST.in.jj2
  - "tests/requirements.txt": "tests/requirements.txt"
  - test.sh: test.sh.jj2
  - test.bat: test.sh.jj2
  - .gitignore: .gitignore.jj2
  - "pyexcel_handsontable/htmlwidgets/css.py": "handsontable/css.py"